# Disable table of contents
page:
  toc: false

# Alternative syntax if the above doesn't work:
defaults:
  toc: false

# Or disable it globally:
site:
  toc: false
name: Retype Docs

on:
  push:
    branches: [ "main" ]   # or "master" if that's your default branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install Retype
        run: npm install -g retypeapp

      - name: Build Retype site
        run: retype build

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: .retype
